spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: register-local
              uri: forward:/api/v1/auth/register
              predicates:
                - Path=/api/v1/auth/register

            - id: auth-service
              uri: http://auth-service:8081
              predicates:
                - Path=/api/v1/auth/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: authCircuitBreaker
                    fallbackUri: forward:/fallback/auth

            - id: user-service
              uri: http://user-service:8080
              predicates:
                - Path=/api/users/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: userCircuitBreaker
                    fallbackUri: forward:/fallback/user

            - id: order-service
              uri: http://order-service:8082
              predicates:
                - Path=/api/v1/orders/**
              filters:
                - name: RewritePath
                  args:
                    regexp: "/api/v1/orders(?<segment>/?.*)"
                    replacement: "/api/orders${segment}"
                - name: CircuitBreaker
                  args:
                    name: orderCircuitBreaker
                    fallbackUri: forward:/fallback/order



server:
  port: 8080

resilience4j:
  circuitbreaker:
    instances:
      authCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      userCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
      orderCircuitBreaker:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5s
        failureRateThreshold: 50

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: DEBUG