apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: system-mongodb
spec:
  serviceName: system-mongodb
  replicas: 1
  selector:
    matchLabels:
      app: system-mongodb
  template:
    metadata:
      labels:
        app: system-mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4
          ports:
            - containerPort: 27017
          livenessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 27017
            initialDelaySeconds: 20
            periodSeconds: 5
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: system-mongodb
spec:
  selector:
    app: system-mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP